# Generated by Django 3.1.6 on 2021-02-12 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxibooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxibooking.customer'),
        ),
    ]
