# Generated by Django 3.1.6 on 2021-02-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxibooking', '0002_auto_20210212_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='destination_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='destination_y',
            field=models.IntegerField(default=0),
        ),
    ]
